[package]
name = "generate_kana_table"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Maki <maki111000664455@gmail.com>"]
description = "Generate Google IME Setting file"

[dependencies]
